FROM node:4-wheezy

MAINTAINER Namlook

RUN apt-get update && apt-get install -y \
        graphicsmagick \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./package.json /app/package.json
RUN npm install -q

COPY ./config/secret.json /app/config/secret.json
COPY ./app /app/app
COPY ./backend /app/backend
COPY ./config /app/config
COPY ./dist /app/dist

# add more files here if you need it
# COPY ./bin /app/bin


ENV NODE_ENV production

EXPOSE 80

CMD ["node", "backend"]
